# Generated by Django 3.0.7 on 2021-12-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.CharField(default='something', max_length=255),
        ),
    ]
